
const EVENTS = {
  CONTRACT_EXPOSED_EVENT: 'Conract Events will come here',
};

const CHAIN_ID = {
  POLYGON: 137,
  MUMBAI: 80001
};

const STAT_INCREMENT = {
  USER_COUNT: 'USER_COUNT',
  UTILITY_COUNT: 'UTILITY_COUNT',
  UTILITY_CLAIMED_COUNT: 'UTILITY_CLAIMED_COUNT',
};

module.exports = {
  CHAIN_ID,
  EVENTS,
  STAT_INCREMENT,
};
